
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package bling;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 27;
  public static final int AND = 13;
  public static final int NE = 22;
  public static final int LT = 18;
  public static final int ELSE = 10;
  public static final int PLUS = 3;
  public static final int OR = 14;
  public static final int RBRACE = 12;
  public static final int RPAREN = 8;
  public static final int WHILE = 26;
  public static final int SEMI = 2;
  public static final int NOT = 15;
  public static final int TRUE = 24;
  public static final int IF = 9;
  public static final int GT = 19;
  public static final int LPAREN = 7;
  public static final int LBRACE = 11;
  public static final int ID = 29;
  public static final int LE = 20;
  public static final int STRING = 30;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int FALSE = 25;
  public static final int GE = 21;
  public static final int MINUS = 4;
  public static final int PRINT = 23;
  public static final int error = 1;
  public static final int LET = 16;
  public static final int EQ = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "IF",
  "ELSE",
  "LBRACE",
  "RBRACE",
  "AND",
  "OR",
  "NOT",
  "LET",
  "EQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "PRINT",
  "TRUE",
  "FALSE",
  "WHILE",
  "MOD",
  "NUMBER",
  "ID",
  "STRING"
  };
}

