
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package bling;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 14;
  public static final int NE = 23;
  public static final int LT = 19;
  public static final int ELSE = 11;
  public static final int PLUS = 3;
  public static final int OR = 15;
  public static final int RBRACE = 13;
  public static final int RPAREN = 9;
  public static final int SEMI = 2;
  public static final int NOT = 16;
  public static final int TRUE = 25;
  public static final int IF = 10;
  public static final int GT = 20;
  public static final int LPAREN = 8;
  public static final int LBRACE = 12;
  public static final int ID = 29;
  public static final int LE = 21;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int DIVIDE = 7;
  public static final int FALSE = 26;
  public static final int GE = 22;
  public static final int MINUS = 4;
  public static final int PRINT = 24;
  public static final int error = 1;
  public static final int LET = 17;
  public static final int EQ = 18;
  public static final int BOOL = 28;
  public static final int UMINUS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "UMINUS",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "IF",
  "ELSE",
  "LBRACE",
  "RBRACE",
  "AND",
  "OR",
  "NOT",
  "LET",
  "EQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "PRINT",
  "TRUE",
  "FALSE",
  "NUMBER",
  "BOOL",
  "ID"
  };
}

